### ISSUE TITLE
Not working....

### ISSUE THREAD

**Issue by GeekyTim** [TheCatLady/docker-qnap-pushover#10]
I have tried installing this on my QNAP NAS (TS453D) but it stops immediately after it starts. I have tried both creating the yaml as instructed, and creating the container from the Docker Hub, but have the same results.

I have created another container on the NAS (CentOS) and that runs without issues.

Am I missing something?

Thanks

**Comment by TheCatLady** [comment]
Hi @GeekyTim, can you provide more details on how you created the container? It sounds like something is not configured properly.

**Edit:** Please also provide logs.

**Comment by GeekyTim** [comment]
I created the container using the yaml (Docker compose) from the readme.

Unfortunately the Container log just states the container started, but not that it stopped (which it did)

**Comment by GeekyTim** [comment]
The docker-compose.yaml contains:

version: '3'
volumes:
  qnap-pushover:
services:
  qnap-pushover:
    image: thecatlady/qnap-pushover
    container_name: qnap-pushover
    environment:
      - PUSHOVER_TOKEN=mine
      - PUSHOVER_RECIPIENT=mine
    volumes:
      - qnap-pushover:/data
      - /etc/logs/event.log:/event.log:ro
    restart: always

Obviously with 'mine' replaced.

**Comment by TheCatLady** [comment]
@GeekyTim Can you set the `LOG_LEVEL` environment variable to `DEBUG` and provide logs?  Try running the following command (you can switch back to using Compose once you get the container to run):

```
docker run -d \
  --name=qnap-pushover \
  -e LOG_LEVEL=DEBUG \
  -e PUSHOVER_TOKEN=<Pushover application API token> \
  -e PUSHOVER_RECIPIENT=<Pushover user and/or group key(s)> \
  -v qnap-pushover:/data \
  -v /etc/logs/event.log:/event.log:ro \
  --restart always \
  thecatlady/qnap-pushover
```

Unfortunately, there's not much I can do to help you unless I can see what is going on. I personally have this working on a TS-653D without issue.

**Comment by TheCatLady** [comment]
@GeekyTim Since you're using a QNAP NAS, one way to access container logs is through Container Station.

Also, since the `docker run` command worked, perhaps you can check the formatting of your Compose YAML?  It's very particular/strict about whitespace/indentation.

**Edit:** Closing this issue since it's been resolved, but feel free to provide additional info or post more comments. 😺

**Comment by GeekyTim** [comment]
Thank you for your help. Really appreciated. I'm now getting notifications.
