### ISSUE TITLE
Distinct filters for event severity

### ISSUE THREAD

**Issue by bennyevangelista** [TheCatLady/docker-qnap-pushover#2]
Hi!
We've already exchanged some ideas on reddit, now I've been using qnap-pushover for a while and I think it could be useful to have a distinct set of included/excluded words for each event level (WARN, INFO, ERROR): in this way I could, for example, receive notifications about all the ERRORS (no filter) while filtering warnings and infos with specific words. Maybe the same thing could be achieved having more containers running and introducing the possibility to set the event severity level to notify (instead of the highest that includes all the lower) and setting each container to listen only to a severity level.

Thanks!

**Comment by TheCatLady** [comment]
Hi @bennyevangelista!  That's a good idea.  Let me think about the best way to go about this!

**Comment by TheCatLady** [comment]
@bennyevangelista Added `NOTIFY_ONLY` parameter in c4e5d2e; this change will enable you to run multiple containers to achieve what you are trying to do.  Please see `README.md` for details on how to configure! 😄
