### ISSUE TITLE
How are you

### ISSUE THREAD

**Issue by iranee** [TheCatLady/docker-qnap-pushover#53]
Many thanks to the author for this script !
I would like to ask, how to run .py directly in the linux shell without deploying docker, and how to parse variables?
I don't need pushover to push, how to use [Bark](https://github.com/Finb/Bark) push instead?
Thanks for answering!

**Comment by TheCatLady** [comment]
> I would like to ask, how to run .py directly in the linux shell without deploying docker, and how to parse variables?

You can review the [Dockerfile](https://github.com/TheCatLady/docker-qnap-pushover/blob/main/Dockerfile).

> I don't need pushover to push, how to use [Bark](https://github.com/Finb/Bark) push instead? Thanks for answering!

Sorry, but this is not supported.  You would need to modify the Python script yourself.
